Output demo.gif

Set Width 1920
Set Height 1080
Set PlaybackSpeed 0.5
Set Theme "Gruvbox Light"

Sleep 1.5s
Type "./MediaLogger-TUI"
Enter
Sleep 1.5s
Enter 2
Type "Shawshank Redemption"
Sleep 250ms
Enter
Down
Enter
Type "1994"
Sleep 250ms
Enter
Down
Enter
Enter
Type "Drama"
Sleep 250ms
Enter
Type "Crime"
Sleep 250ms
Enter
Escape 2
Down
Enter
Down 2
Enter
Sleep 250ms
Down 5 Enter
Sleep 250ms
Escape Down
Right 3
Sleep 250ms
Down
Sleep 250ms
Enter
Sleep 3.5s
Ctrl+C
